# Generated by Django 2.2.8 on 2019-12-22 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('provider_event_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('sale_start_date', models.DateTimeField()),
                ('sale_end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('provider_date_id', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='event.Event')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('capacity', models.PositiveIntegerField()),
                ('rest', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('numbered', models.BooleanField(default=False)),
                ('provider_zone_id', models.PositiveIntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='event.EventDate')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('provider_resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='event.ProviderResource')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.Provider'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['date'], name='event_zone_date_id_11a58a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdate',
            index=models.Index(fields=['event'], name='event_event_event_i_3f3f32_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['provider'], name='event_event_provide_b199c9_idx'),
        ),
    ]
